using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum CountType
{
	// ターゲットが必要ないもの
	NONE = 0,
	PP = 1,
	MAX_PP = 2,
	SHIELD = 3,
	TURN = 4,
	ATTACK_COUNT = 5,
	LEADER_HP = 5,
	TURN_PLAY_COUNT = 11,
	TURN_DISCARD_COUNT = 12,
	TURN_DESTROY_COUNT = 13,
	ACTIVATE_POWER = 21,
	LAST_ABILITY_POWER = 22,
	ACTIVATE_COUNT = 31,
	BEFORE_ACTIVATE_COUNT = 32,
	BACK_WATER = 33,

	// ターゲットが必要なもの
	CARD_COUNT = 51,
	DISTINCT_CARD_ID_COUNT = 52,
	COST = 61,
	ATTACK = 62,
	HP = 63,
	CUSTOM_POWER = 64,
	SPIRAL = 65,
	RETURN_COUNT = 66,
	SOUL_CHARGE = 67,
	SELF_HARM_COUNT = 69,
	MAX_HP = 68,
	DESTROYED_MOMENT_COST = 71,
	DESTROYED_MOMENT_ATTACK = 72,
	DESTROYED_MOMENT_HP = 73,
	BOUNCED_MOMENT_COST = 74,
	BOUNCED_MOMENT_ATTACK = 75,
	BOUNCED_MOMENT_HP = 76,
	CHARGE_COUNT = 77,
	PROPERTY_COUNT = 78,
	RELEASE_COUNT = 79,
	UNIQUE_COUNTER = 80,
}
