using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum QuestType
{
	NONE = 0,
	TURN = 1,
	ATTACK_COUNT = 2,
	DRAW_COUNT = 3,
	CONSUME_PP = 4,
	PLAY_COUNT = 21,
	BOUNCE_COUNT = 22,
	LEFT_FAIRY_COUNT = 23,
	DISCARD_COUNT = 31,
	ENEMY_TURN_END_SHIELD = 41,
	DESTROY_AMULET_COUNT = 51,
	ADVANCE_COUNT = 52,
	MAX_PP = 61,
	PLAY_7_MORE_COUNT = 62,
	DESTROY_UNIT_COUNT = 71,
	RALLY_COUNT = 81,
	SPIRAL_CHARGE_COUNT = 91
}
